version: "3"
services:
  application:
    image: tkgregory/sample-metrics-application:latest
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus:latest
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
        - "9090:9090"